### ISSUE TITLE
Tag menu doesn't work in 3.1

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#369]
```
Traceback (most recent call last):
  File "/home/mario/.virtualenvs/ghide-3.1-dev/lib/python3.5/site-packages/ghini.desktop-3.1.3-py3.5.egg/bauble/plugins/tag/__init__.py", line 276, in on_new_button_clicked
    tags_menu_manager.reset(tag)
  File "/home/mario/.virtualenvs/ghide-3.1-dev/lib/python3.5/site-packages/ghini.desktop-3.1.3-py3.5.egg/bauble/plugins/tag/__init__.py", line 72, in reset
    self.menu_item.remove_submenu()
AttributeError: 'MenuItem' object has no attribute 'remove_submenu'
```

**Comment by mfrasca** [comment]
this was a simple one: there is no such function and we don't need it either.
